---
# Tasks specific for RedHat systems

- name: "RedHat | Use EPEL package name"
  set_fact:
    zabbix_agent_package: "zabbix{{ zabbix_short_version }}-agent"
  when:
    - zabbix_repo == "epel"
  tags:
    - zabbix-agent
    - init

- name: "RedHat | Install basic repo file"
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"
  become: yes
  tags:
    - zabbix-agent

- name: "RedHat | Installing zabbix-agent"
  yum:
    pkg: "{{ zabbix_agent_package }}"
    state: "{{ zabbix_agent_package_state }}"
  become: yes
  tags:
    - init
    - zabbix-agent

- name: "Install policycoreutils-python"
  yum:
    name: policycoreutils-python
    state: installed
  when: zabbix_selinux
  tags:
    - init
    - zabbix-agent

- name: "RedHat | Enable the service"
  service:
    name: "{{ zabbix_agent_service }}"
    enabled: yes
    use: service
  become: yes
  tags:
    - zabbix-agent
    - init
    - service

- name: "RedHat | Install yum-plugin-security"
  yum:
    name: yum-plugin-security
    state: installed
  tags:
    - init
    - zabbix-agent
